### ISSUE TITLE
A request with an array of files not working

### ISSUE THREAD

**Issue by jamesj2** [alireaza/laravel-form-data#1]
An array of files isn't working for me.  If I change the form to give them a unique name it works.  Which makes it more difficult to iterate.  Looks like it's not expected children in the array.

```log
ErrorException: Undefined array key "tmp_name" in .../vendor/alireaza/laravel-form-data/src/Middleware/FormData.php:33
```

**Comment by alireaza** [comment]
Hi @jamesj2,

Thanks a lot for contributing and reporting this issue.
The problem was checked and fixed, now you can use the new version.

Best regards,
@alireaza
