### ISSUE TITLE
[Question] There's any plan to support Laravel 11? 

### ISSUE THREAD

**Issue by jeffersonsouza** [alireaza/laravel-form-data#2]
I am just wondering :) 

Your package is quite helpful and I am currently evaluating the migration to L11.

**Comment by alireaza** [comment]
Hi @jeffersonsouza,

First and foremost, I sincerely apologize for the delayed response. Life and work have been keeping me quite busy, but I truly appreciate your patience.

Thank you so much for raising this issue and for your interest in seeing the package support Laravel 11! I'm glad to hear that you find the package helpful, and I appreciate your initiative in evaluating the migration to Laravel 11.

I also want to express my gratitude for the Merge Request you submitted. I'm happy to inform you that it has been reviewed and approved. Your contribution is invaluable, and it’s thanks to efforts like yours that open-source projects continue to thrive.

If you have any additional suggestions, ideas, or feedback, please don't hesitate to share. Your input is always welcome!

Thanks again for your support and contribution.

Best regards,
@AliReaza
